spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_robot

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
                  
      bindings:
        members:
          destination: members
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        authorization:
          destination: authorization
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouShuangkouGameRoom:
          destination: wenzhouShuangkouGameRoom
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

        wenzhouGameRoom:
          destination: wenzhouGameRoom
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

        dianpaoGameRoom:
          destination: dianpaoGameRoom
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

        fangpaoGameRoom:
          destination: fangpaoGameRoom
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

        ruianGameRoom:
          destination: ruianGameRoom
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

        ruianMajiangGame:
          destination: ruianMajiangGame
          group: qipai_robot
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json

  application:
    name: qipai_robot
server:
  port: 90
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
